import sys
import os
import asyncio

# -------------------------------
# PATH FIX (to access core engine)
# -------------------------------
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ENGINE_PATH = os.path.join(BASE_DIR, "swarm_ai-main")

if ENGINE_PATH not in sys.path:
    sys.path.append(ENGINE_PATH)


import uuid
from typing import Dict, Any, List
from core.workflow import run_swarm


# -------------------------------
# STATE STORE (in-memory for now)
# -------------------------------
STATE_DB: Dict[str, Dict[str, Any]] = {}


# -------------------------------
# SESSION INIT
# -------------------------------
def initialize_session(problem: str) -> Dict[str, Any]:
    state = {
        "id": str(uuid.uuid4()),
        "problem": problem,
        "iteration": 0,
        "ideas": []
    }
    STATE_DB[state["id"]] = state
    return state


# -------------------------------
# RUN ONE ITERATION
# -------------------------------
def run_iteration(state: Dict[str, Any]) -> Dict[str, Any]:
    problem = state["problem"]

    # 🔥 FIX: run async swarm properly
    result = asyncio.run(run_swarm(problem))

    ideas = []

    # 🔁 Normalize output
    raw_ideas = getattr(result, "top_ideas", []) or getattr(result, "all_ideas", [])

    for idea in raw_ideas:
        ideas.append({
            "content": getattr(idea, "content", str(idea)),
            "parent_ids": getattr(idea, "parent_ids", []),
            "action_type": getattr(idea, "action_type", "generate"),
            "reason": getattr(idea, "reason", "Generated by swarm"),
            "score": getattr(idea, "score", 0),
            "votes": getattr(idea, "votes", 0),
        })

    state["iteration"] += 1
    state["ideas"] = ideas

    return state


# -------------------------------
# SCORE + SELECT BEST IDEAS
# -------------------------------
def score_and_select(state: Dict[str, Any]) -> Dict[str, Any]:
    ideas = state["ideas"]

    for idea in ideas:
        if idea["score"] == 0:
            idea["score"] = len(idea["content"])

    ideas.sort(key=lambda x: x["score"], reverse=True)

    state["ideas"] = ideas
    return state


# -------------------------------
# GET CURRENT STATE
# -------------------------------
def get_state(state: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "problem": state["problem"],
        "iteration": state["iteration"],
        "ideas": state["ideas"]
    }